### ISSUE TITLE
[processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`

### ISSUE THREAD

**Issue by CherryDT** [anseki/vscode-color#24] opened 2017-01-25 19:20 UTC
- Extension Version: 0.2.2
- VS Code Version: 1.9.0-insider
- OS Version: Windows 10 14986
- Node.js Version (result of command `node -v`): 7.2.1
- NPM Version (result of command `npm -v`): 3.10.10

Steps to Reproduce:

1. Install the extension
2. Try to pick a color
3. Wait a while while it says "Please wait while setting up the extension"

Result:
> [processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`

Log (All lines):
```
Overwriting extension <<.js>> to now point to mime <<text/x-javascript>>
mime.ts:59 Overwriting extension <<.tag>> to now point to mime <<text/x-htmltag>>
mime.ts:59 Overwriting extension <<.log>> to now point to mime <<text/x-log>>
mime.ts:59 Overwriting extension <<.vbs>> to now point to mime <<text/x-vbscript>>
mainThreadExtensionService.ts:103 [C:/Users/david/.vscode-insiders/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: lattet.$localShowMessage @ mainThreadExtensionService.ts:103
mainThreadExtensionService.ts:103 [C:/Users/david/.vscode-insiders/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: tplt.$localShowMessage @ mainThreadExtensionService.ts:103
mainThreadExtensionService.ts:103 [C:/Users/david/.vscode-insiders/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: tst.$localShowMessage @ mainThreadExtensionService.ts:103
mainThreadExtensionService.ts:103 [C:/Users/david/.vscode-insiders/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: hamlt.$localShowMessage @ mainThreadExtensionService.ts:103
mainThreadExtensionService.ts:103 [C:/Users/david/.vscode-insiders/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: erbt.$localShowMessage @ mainThreadExtensionService.ts:103
mainThreadExtensionService.ts:109 [C:/Users/david/.vscode-insiders/extensions/fknop.vscode-npm-3.3.0]: Command `npm-script.start` appears multiple times in the `commands` section.
mainThreadExtensionService.ts:109 [C:/Users/david/.vscode-insiders/extensions/fknop.vscode-npm-3.3.0]: Command `npm-script.test` appears multiple times in the `commands` section.
keybindingsRegistry.ts:109 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2601  for  bookmarks.toggle
keybindingsRegistry.ts:109 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2602  for  bookmarks.jumpToNext
keybindingsRegistry.ts:109 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2600  for  bookmarks.jumpToPrevious
keybindingsRegistry.ts:109 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2604  for  extension.createNewFile
keybindingsRegistry.ts:109 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2593  for  extension.baseConverter.anyToAny
keybindingsRegistry.ts:109 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  170002978  for  docthis.documentThis
keybindingsRegistry.ts:109 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  170068514  for  docthis.documentEverything
keybindingsRegistry.ts:109 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  171182626  for  docthis.documentEverythingVisible
keybindingsRegistry.ts:109 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2593  for  extension.convertSelection
keybindingsRegistry.ts:109 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  2595  for  PowerShell.ExpandAlias
keybindingResolver.ts:193 Conflict detected, command `editor.action.formatSelection` cannot be triggered by ctrl+k due to extension.filterText
keybindingResolver.ts:193 Conflict detected, command `workbench.action.togglePanel` cannot be triggered by ctrl+j due to extension.join-lines
keybindingResolver.ts:193 Conflict detected, command `workbench.action.openRecent` cannot be triggered by ctrl+r due to npm-script.showOutput
keybindingResolver.ts:193 Conflict detected, command `editor.debug.action.toggleBreakpoint` cannot be triggered by f9 due to sortLines.sortLines
keybindingResolver.ts:193 Conflict detected, command `workbench.action.openRecent` cannot be triggered by ctrl+r due to npm-script.run
keybindingResolver.ts:193 Conflict detected, command `workbench.action.openRecent` cannot be triggered by ctrl+r due to npm-script.rerun-last-script
keybindingResolver.ts:193 Conflict detected, command `PowerShell.OnlineHelp` cannot be triggered by ctrl+f1 due to extension.launchHelp
keybindingResolver.ts:193 Conflict detected, command `workbench.action.openRecent` cannot be triggered by ctrl+r due to npm-script.terminate-script
keybindingResolver.ts:193Conflict detected, command `workbench.action.openRecent` cannot be triggered by ctrl+r due to npm-script.test
extensionHost.ts:261[Extension Host] git (vscode.git) uses PROPOSED API which is subject to change and removal without notice
extensionHost.ts:261[Extension Host] DEPRECATION: @memoize is deprecated and will be removed shortly. Use @decorate with lodash's memoize helper.

  https://github.com/jayphelps/core-decorators.js#decorate
extensionHost.ts:261[Extension Host] [C:/Users/david/.vscode-insiders/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: latted.logExtensionHostMessage @ extensionHost.ts:261
extensionHost.ts:261[Extension Host] [C:/Users/david/.vscode-insiders/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: tpld.logExtensionHostMessage @ extensionHost.ts:261
extensionHost.ts:261[Extension Host] [C:/Users/david/.vscode-insiders/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: tsd.logExtensionHostMessage @ extensionHost.ts:261
extensionHost.ts:261[Extension Host] [C:/Users/david/.vscode-insiders/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: hamld.logExtensionHostMessage @ extensionHost.ts:261
extensionHost.ts:261[Extension Host] [C:/Users/david/.vscode-insiders/extensions/wcwhitehead.bootstrap-3-snippets-0.0.9]: Unknown language in `contributes.snippets.language`. Provided value: erbd.logExtensionHostMessage @ extensionHost.ts:261
extensionHost.ts:261[Extension Host] [C:/Users/david/.vscode-insiders/extensions/fknop.vscode-npm-3.3.0]: Command `npm-script.start` appears multiple times in the `commands` section.
extensionHost.ts:261[Extension Host] [C:/Users/david/.vscode-insiders/extensions/fknop.vscode-npm-3.3.0]: Command `npm-script.test` appears multiple times in the `commands` section.
extensionHost.ts:261[Extension Host] Windows_NT
extensionHost.ts:261[Extension Host] Uncaught Exception:  Error: Language client is not ready yetd.logExtensionHostMessage @ extensionHost.ts:261
extensionHost.ts:261[Extension Host] Error: Language client is not ready yet
    at LanguageClient.sendRequest (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\css\node_modules\vscode-languageclient\lib\main.js:582:19)
    at colorRequestor (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\css\client\out\cssMain.js:43:23)
    at updateDecorationForEditor (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\css\client\out\colorDecorators.js:67:9)
    at Timeout._onTimeout (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\css\client\out\colorDecorators.js:58:25)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)d.logExtensionHostMessage @ extensionHost.ts:261
shell.ts:433Language client is not ready yet: Error: Language client is not ready yet
    at LanguageClient.sendRequest (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\css\node_modules\vscode-languageclient\lib\main.js:582:19)
    at colorRequestor (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\css\client\out\cssMain.js:43:23)
    at updateDecorationForEditor (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\css\client\out\colorDecorators.js:67:9)
    at Timeout._onTimeout (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\extensions\css\client\out\colorDecorators.js:58:25)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)e.onUnexpectedError @ shell.ts:433
shell.ts:433Failed to execute gite.onUnexpectedError @ shell.ts:433
winjs.base.js:45WARNING: Promise with no error callback:140
winjs.base.js:46Object
extensionHost.ts:261[Extension Host] rejected promise not handled within 1 second
extensionHost.ts:261[Extension Host] Start child process...
extensionHost.ts:261[Extension Host] Start initializing module...
extensionHost.ts:261[Extension Host] Node.js@6.5.0
extensionHost.ts:261[Extension Host] Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.i._load (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:19120)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at getNpm (C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:139:15)
    at initModule (C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:468:34)
extensionHost.ts:261[Extension Host] Continue trying to get NPM...
extensionHost.ts:261[Extension Host] Try to get NPM via usage info.
extensionHost.ts:261[Extension Host] NPM@3.10.10
extensionHost.ts:261[Extension Host] NPM directory path: C:\Program Files\nodejs\node_modules\npm
extensionHost.ts:261[Extension Host] NPM resolved path: C:\Program Files\nodejs\node_modules\npm\lib\npm.js
extensionHost.ts:261[Extension Host] Base directory path: C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2
extensionHost.ts:261[Extension Host] Retry (Error: Cannot find module 'electron-prebuilt')
extensionHost.ts:261[Extension Host] Try to load: C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\esparse -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\esprima\bin\esparse.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\esvalidate -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\esprima\bin\esvalidate.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\mkdirp -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\mkdirp\bin\cmd.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\ncp -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\ncp\bin\ncp
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\semver -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\semver\bin\semver
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\strip-indent -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\strip-indent\cli.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\strip-json-comments -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\strip-json-comments\cli.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\rc -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\rc\index.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\har-validator -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\har-validator\bin\har-validator
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\sshpk-conv -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\sshpk\bin\sshpk-conv
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\sshpk-sign -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\sshpk\bin\sshpk-sign
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\sshpk-verify -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\sshpk\bin\sshpk-verify
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\uuid -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\uuid\bin\uuid
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\pretty-bytes -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\pretty-bytes\cli.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\rimraf -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\rimraf\bin.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\nugget -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\nugget\bin.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\electron-download -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\electron-download\cli.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\extract-zip -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\extract-zip\cli.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\electron -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\electron-prebuilt\cli.js
extensionHost.ts:261[Extension Host] C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\js-yaml -> C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2\node_modules\js-yaml\bin\js-yaml.js
extensionHost.ts:261[Extension Host] Spawn in silent-mode: C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
extensionHost.ts:261[Extension Host] vscode-color@0.2.2 C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2
+-- comma-separated-values@3.6.4 
+-- js-yaml@3.7.0 
| +-- argparse@1.0.9 
| | `-- sprintf-js@1.0.3 
| `-- esprima@2.7.3 
`-- process-bridge@0.3.6 
  `-- semver@5.3.0 

extensionHost.ts:261[Extension Host] Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1
    at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)d.logExtensionHostMessage @ extensionHost.ts:261
messageService.ts:126[processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1e.doShow @ messageService.ts:126
shell.ts:433Failed to execute gite.onUnexpectedError @ shell.ts:433
winjs.base.js:45WARNING: Promise with no error callback:144
winjs.base.js:46Object
extensionHost.ts:261[Extension Host] rejected promise not handled within 1 second
```

**Comment by anseki** [comment] 2017-01-26 02:05
Hi @CherryDT, thank you for the comment.

It seems a duplicate of #7.

The installing might have failed.
Try to re-install the extension.

1. Remove `C:\Users\david\.vscode-insiders\extensions\anseki.vscode-color-0.2.2` directory.
2. Install Color Picker again.

Please comment to #7 about this issue.

**Closed as completed by anseki** 2017-01-26 02:05 UTC

**Comment by lanten** [comment] 2017-04-24 05:55
i reinstall 3 times , still error
cd extension directory  then

> @anseki removed unsafe commands

the extension is work

**Comment by anseki** [comment] 2017-04-24 15:27
Hi @lanten, thank you for the report.

Did you see the same error that is `postinstall: node install.js`?
If so, NPM cache data might be broken.
