### ISSUE TITLE
The Color Picker Doesn't Start or show up

### ISSUE THREAD

**Issue by SeriousSamV** [anseki/vscode-color#36] opened 2017-05-28 18:10 UTC
- Extension Version: anseki.vscode-color@0.4.1
- VS Code Version: Version 1.12.2
- OS Version: Ubuntu 16.10, Linux 4.8.0-53-generic
- Node.js Version (result of command `node -v`): v7.10.0
- NPM Version (result of command `npm -v`): 4.2.0

Steps to Reproduce:

1. Press {Alt+c, c/p} or try to open the color picker by any means. 

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
workbench.main.js:28 Overwriting extension <<.java>> to now point to mime <<text/x-pde>>
(anonymous) @ workbench.main.js:28
workbench.main.js:28 Overwriting extension <<.fs>> to now point to mime <<text/x-glsl>>
(anonymous) @ workbench.main.js:28
workbench.main.js:29 [Extension Host] vscode-icons is active!
workbench.main.js:29 [Extension Host] Start child process...
workbench.main.js:29 [Extension Host] Error: ENOENT: no such file or directory, open '/home/sam/.vscode/extensions/anseki.vscode-color-0.4.1/node_modules/electron-prebuilt/path.txt'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.<anonymous> (/home/sam/.vscode/extensions/anseki.vscode-color-0.4.1/node_modules/electron-prebuilt/index.js:4:42)
    at Object.<anonymous> (/home/sam/.vscode/extensions/anseki.vscode-color-0.4.1/node_modules/electron-prebuilt/index.js:6:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
d.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:28 [processBridge]: Error: ENOENT: no such file or directory, open '/home/sam/.vscode/extensions/anseki.vscode-color-0.4.1/node_modules/electron-prebuilt/path.txt'
```

**Comment by anseki** [comment] 2017-05-28 18:39
Hi @Samuel0Paul, thank you for the comment.

It seems that this is a duplicate of #7.
The Electron in your computer is broken. Re-install the extension.
And please comment to #7 about this issue if you need.

**Closed as completed by anseki** 2017-05-28 18:39 UTC
