### ISSUE TITLE
Error: Cannot find module 'ansi'

### ISSUE THREAD

**Issue by dz0ny** [anseki/vscode-color#18] opened 2016-11-20 13:03 UTC
- Extension Version: 0.2.1
- VS Code Version: 1.7.1
- OS Version: Linux
- Node.js Version (result of command `node -v`): Not available globally
- NPM Version (result of command `npm -v`): Not available globally

Steps to Reproduce:

1. Select Color Picker from command palette

Log:
```
Error: Cannot find module 'ansi'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.M.d._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:28523)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/npm/lib/ls.js:15:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.M.d._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:28523)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/npm/lib/install.js:110:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.M.d._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:28523)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.get [as install] (/usr/share/npm/lib/npm.js:192:17)
    at /home/dz0ny/.vscode/extensions/anseki.vscode-color-0.2.1/node_modules/process-bridge/process-bridge.js:255:19
    at EventEmitter.<anonymous> (/home/dz0ny/.vscode/extensions/anseki.vscode-color-0.2.1/node_modules/process-bridge/process-bridge.js:391:19)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by anseki** [comment] 2016-11-20 13:26
Hi @dz0ny,
It seems that this is a duplicate of #10.
Please read that issue, and comment to that if you need.
And also, you should make Node.js and NPM available.
See: https://github.com/anseki/vscode-color#install

**Closed as completed by anseki** 2016-11-20 13:26 UTC
