### ISSUE TITLE
Error? Bug? 

### ISSUE THREAD

**Issue by crper** [anseki/vscode-color#21] opened 2016-12-12 16:54 UTC
- Extension Version: 0.2.2
- VS Code Version: 1.7.1
- OS Version: Win10 redstone 1
- Node.js Version (result of command `node -v`): 6.9.1
- NPM Version (result of command `npm -v`): 3.8+

Steps to Reproduce:

1. install extendsion
2. `alt+c p` or global command 'color picker' , can show GUI.....everytime show this status;

![image](https://cloud.githubusercontent.com/assets/8272877/21108069/b67e955e-c0ce-11e6-92d4-d38bb6f99153.png)

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
Host] Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.M.d._load (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:28523)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at getNpm (C:\Users\crper\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:139:15)
    at initModule (C:\Users\crper\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\crper\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\crper\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\crper\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\crper\.vscode\extensions\anseki.vscode-color-0.2.2\lib\color-helper.js:180:15)
    at exports.pick (C:\Users\crper\.vscode\extensions\anseki.vscode-color-0.2.2\lib\color-helper.js:220:24)
    at t.$executeContributedCommand (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:25694)
    at t.e.handle (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:10602)
    at s (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:21356)
    at p (d:\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:22033)
```

I shold install node and npm on global environment!!!

![image](https://cloud.githubusercontent.com/assets/8272877/21108229/7900802e-c0cf-11e6-832f-17e6c144077a.png)

**Comment by anseki** [comment] 2016-12-12 17:31
Hi @crper,
It seems that this is a duplicate of #14.
Please read that issue, and comment to that if you need.
And also, that seems a part of log.
Your NPM does not seem to be available in the VS Code process.

**Closed as completed by anseki** 2016-12-12 17:31 UTC
