### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by ssine** [anseki/vscode-color#67] opened 2018-01-07 11:43 UTC
- Extension Version:0.4.5
- VS Code Version:1.19.1
- OS Version:win10 1709
- Node.js Version (result of command `node -v`):v8.1.3
- NPM Version (result of command `npm -v`):5.0.3

Steps to Reproduce:

1. install the extension in the VS Marketplace
2. press Alt+C P

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
console.ts:123 [Extension Host] Start child process...
console.ts:123 [Extension Host] Error: ENOENT: no such file or directory, open 'C:\Users\96336\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\path.txt'
	at Object.fs.openSync (fs.js:584:18)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
	at Object.fs.readFileSync (fs.js:491:33)
	at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:505:29)
	at Object.<anonymous> (C:\Users\96336\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\index.js:4:42)
	at Object.<anonymous> (C:\Users\96336\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\index.js:6:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.J.X.t.getExtensionPathIndex.then.o._load (d:\Software\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:709)
	at Module.require (module.js:498:17)
	at getHostCmd (C:\Users\96336\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:316:41)
	at C:\Users\96336\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
	at Object.exports.sendRequest (C:\Users\96336\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
	at pickConvert (C:\Users\96336\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
	at exports.pick (C:\Users\96336\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
	at e.$executeContributedCommand (d:\Software\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:416:270)
	at t.e.invoke (d:\Software\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:516:87)
	at e._invokeHandler (d:\Software\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:580)
	at e._receiveOneMessage (d:\Software\VSCode\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:270)

messageService.ts:126 [processBridge]: Error: ENOENT: no such file or directory, open 'C:\Users\96336\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\path.txt'
```

**Comment by anseki** [comment] 2018-01-07 11:53
Hi @ssine, thank you for the report.

It seems that this is a duplicate of [past issues](https://github.com/anseki/vscode-color/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22ENOENT%22%20%22path.txt%22).
The Electron in your computer is broken. Re-install the extension.
And please comment to #7 (not here) about this issue if you need.

**Closed as completed by anseki** 2018-01-07 11:53 UTC
