### ISSUE TITLE
[processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`

### ISSUE THREAD

**Issue by imgwho** [anseki/vscode-color#20] opened 2016-12-11 01:21 UTC
- Extension Version:
- VS Code Version: 1.7.2
- OS Version: Windows 10 (1607)
- Node.js Version (result of command `node -v`): v4.6.0
- NPM Version (result of command `npm -v`): 2.15.9

Steps to Reproduce:

1. 
2. 

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Looking for parseable documents...
[Extension Host] vscode-icons is active!
[Extension Host] Found all parseable documents.
[Extension Host] Parsing documents and looking for CSS class definitions...
[Extension Host] Sumary:
[Extension Host] 126 parseable documents found
[Extension Host] 14440 CSS class definitions found
[Extension Host] 1076 unique CSS class definitions found
[Extension Host] 5 failed attempts to parse. List of the documents:
[Extension Host] /d:/imgwh/Desktop/Practice/myFocusDemo/js/mf-pattern/mF_YSlider.css
/d:/imgwh/Desktop/Practice/movie/node_modules/grunt-contrib-less/node_modules/less/test/css/media.css
/d:/imgwh/Desktop/Practice/movie/node_modules/grunt-contrib-less/node_modules/less/test/css/property-name-interp.css
/d:/imgwh/Desktop/Practice/movie/node_modules/grunt-contrib-less/node_modules/less/test/css/import-inline.css
/d:/imgwh/Desktop/Practice/movie/node_modules/grunt-contrib-less/node_modules/less/test/css/compression/compression.css

[Extension Host] MANY messages are being SEND FROM the extension host!
[Extension Host] SEND during 1sec: message_count=254, total_len=381
[Extension Host] Start child process...
[Extension Host] Start initializing module...
[Extension Host] Node.js@6.5.0
[Extension Host] Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.M.d._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:28523)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at getNpm (C:\Users\imgwh\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:139:15)
    at initModule (C:\Users\imgwh\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:220:10)
    at getHostCmd (C:\Users\imgwh\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\imgwh\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\imgwh\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:468:34)
[Extension Host] Continue trying to get NPM...
[Extension Host] Try to get NPM via usage info.
[Extension Host] NPM@2.15.9
[Extension Host] NPM directory path: C:\Program Files\nodejs\node_modules\npm
[Extension Host] NPM resolved path: C:\Program Files\nodejs\node_modules\npm\lib\npm.js
[Extension Host] Base directory path: C:\Users\imgwh\.vscode\extensions\anseki.vscode-color-0.2.2
[Extension Host] Retry (Error: Cannot find module 'electron-prebuilt')
[Extension Host] Try to load: C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js
[Extension Host] Spawn in silent-mode: C:\Windows\system32\cmd.exe /d /s /c node install.js
[Extension Host] Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1
    at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
setSelections on invisble editor
[processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1

```

**Comment by anseki** [comment] 2016-12-11 01:36
Hi @imgwho, 

It seems that this is a duplicate of https://github.com/anseki/vscode-color/issues/7#issuecomment-239191756.
Try to do the my recommendation in that issue, and please comment to that issue about this issue.

**Closed as completed by anseki** 2016-12-11 01:36 UTC
