### ISSUE TITLE
[processBridge]: Error: ENOENT: no such file or directory, open 'C:\Users\vimcaw\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\path.txt'

### ISSUE THREAD

**Issue by vimcaw** [anseki/vscode-color#53] opened 2017-08-10 15:25 UTC
- Extension Version: 0.4.5
- VS Code Version: 1.14.2
- OS Version: Windows10-1703
- Node.js Version (result of command `node -v`): 6.11.2
- NPM Version (result of command `npm -v`): 3.10.10

Steps to Reproduce:

1. Alt + C P

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
workbench.main.js:28 Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  e  for  extension.toggleRegexPreview
e._assertNoCtrlAlt @ workbench.main.js:28
workbench.main.js:29 [Extension Host] vscode-icons is active!
workbench.main.js:29 [Extension Host] Start child process...
workbench.main.js:29 [Extension Host] Error: ENOENT: no such file or directory, open 'C:\Users\vimcaw\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\path.txt'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.<anonymous> (C:\Users\vimcaw\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\index.js:4:42)
    at Object.<anonymous> (C:\Users\vimcaw\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\index.js:6:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
h.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:28 [processBridge]: Error: ENOENT: no such file or directory, open 'C:\Users\vimcaw\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\path.txt'
e.doShow @ workbench.main.js:28
```

**Comment by anseki** [comment] 2017-08-10 15:52
It seems that this is a duplicate of [past issues](https://github.com/anseki/vscode-color/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22ENOENT%22%20%22path.txt%22).
The Electron in your computer is broken. Re-install the extension.
And please comment to #7 (not here) about this issue if you need.

**Closed as completed by anseki** 2017-08-10 15:52 UTC
