### ISSUE TITLE
electron-prebuilt@0.37.3 postinstall: `node install.js`

### ISSUE THREAD

**Issue by mxdyyt1314** [anseki/vscode-color#31] opened 2017-05-03 02:16 UTC
- Extension Version:0.4.1
- VS Code Version:1.11.2
- OS Version:windows 10 enterprise
- Node.js Version (result of command `node -v`):6.5
- NPM Version (result of command `npm -v`):3.10.10

Steps to Reproduce:

1. run color-picker
2.  Error: electron-prebuilt@0.37.3 postinstall: `node install.js`

**Comment by anseki** [comment] 2017-05-03 08:29
Hi @mxdyyt1314, thank you for the comment.

It seems a duplicate of https://github.com/anseki/vscode-color/issues?utf8=%E2%9C%93&q=is%3Aissue%20postinstall.
Please comment to #7 if you need, not here.

**Closed as completed by anseki** 2017-05-03 08:29 UTC
