### ISSUE TITLE
[processBridge]: Error: ENOENT: no such file or directory, open 'C:\Users\ADKi\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\path.txt'

### ISSUE THREAD

**Issue by DukeAnn** [anseki/vscode-color#44] opened 2017-06-14 03:37 UTC
[processBridge]: Error: ENOENT: no such file or directory, open 'C:\Users\ADKi\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\path.txt'

**Comment by anseki** [comment] 2017-06-14 05:35
Hi @DukeAnn, thank you for the report.
Could you give me details?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by cjlaravel** [comment] 2017-06-14 06:00
[Extension Host] Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\path.txt'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.<anonymous> (C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\index.js:4:42)
    at Object.<anonymous> (C:\Users\Administrator\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\index.js:6:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by anseki** [comment] 2017-06-14 06:06
Hi @ fujianxiamen, thank you for the report.
Could you give me details?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by DukeAnn** [comment] 2017-06-15 01:30
A dialog box is shown by pressing Alt + C P keys or command Pick Color. If a cursor is positioned on a string that is color notation at that time, that string is selected as target for editing.

[https://github.com/anseki/vscode-color/raw/master/s-01.gif](url)

**Comment by anseki** [comment] 2017-06-15 02:31
@DukeAnn,
Could you give me details?
Please see this:
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by andreroggeri** [comment] 2017-06-17 01:03
@anseki it seems that is missing a slash bar on path.

Is that normal ? 
'C:\Users\AD**Ki.vscode**\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\path.txt'
'C:\Users\Admini**strator.vscode**\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\path.txt'

**Comment by anseki** [comment] 2017-06-17 01:08
Hi @andreroggeri, thank you for the report.
Sorry, what do you mean? Which slash bar?

Also, Could you give me details?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by anseki** [comment] 2017-06-17 01:10
Ah, I see. I understand slash bar 😄

**Comment by andreroggeri** [comment] 2017-06-17 01:10
I think the path for .vscode folder is wrong.

This
C:\Users\Administrator.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\path.txt

Should be:

'C:\Users\Administrator** \\ **.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\path.txt'

**Comment by anseki** [comment] 2017-06-17 01:15
I think that the slash is not the root cause, and the extension does not create the path.
Could you give me details?
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by andreroggeri** [comment] 2017-06-17 01:29
I fixed this error by reinstalling the extension.

But now there is another problem (I'll report on another issue)

**Comment by anseki** [comment] 2017-06-17 04:37
Unfortunately, no reply came from @DukeAnn, and I close this issue.

**Closed as completed by anseki** 2017-06-17 04:37 UTC
