### ISSUE TITLE
Please wait a while for setting up the extension...

### ISSUE THREAD

**Issue by warpdesign** [anseki/vscode-color#13] opened 2016-10-05 12:05 UTC
- Extension Version: 0.1.11
- VS Code Version: 1.6.0-insider (2016-10-01)
- OS Version: Windows 10
- Node.js Version (result of command `node -v`): 6.5.0
- NPM Version (result of command `npm -v`): 2.5..19

Steps to Reproduce:
1. open a css file
2. hover some color definition, open palette and choose "pick color"

When trying to open the color picker, I'm getting this message at the bottom of the window: `Please wait a while for setting up the extension...`. After a sec or two, message disappears, and appears again, endlessly. Nothing happens (the color picker isn't opened).

**Comment by anseki** [comment] 2016-10-05 14:06
Hi @warpdesign, thank you for the report.

That seems the correct behavior.
See https://github.com/anseki/vscode-color#install

Or, do you mean that you waited a long time (e.g. 10 mins?)?
In that case, could you please show me the log?
BTW,  your NPM v2.5 seems too old (it was contained in Node.JS v0.12, maybe), it might be unrelated to the issue.

**Comment by anseki** [comment] 2016-10-17 01:13
No reply came, and I close this issue.

**Closed as completed by anseki** 2016-10-17 01:13 UTC

**Comment by CalicoX** [comment] 2016-12-09 15:39
I meet this problem 'please wait a while for setting up the extension ' again.node -v 6.9.2 npm -v 3.10.9
OS macOS sierra. I can't fix this. I install from the vscode extension shop and when I try to press alt+c and p, the bottom of the window always appear Pleas wait a while for setting up the extension. how can I fix this problem? Thx!

**Comment by anseki** [comment] 2016-12-09 15:56
Hi @CalicoX,

That seems the correct behavior.
See https://github.com/anseki/vscode-color#install
Please wait a while for setting up the extension without closing VS Code.

Or, do you mean that you waited a long time?

**Comment by huyinjie** [comment] 2017-03-02 13:29
@anseki 
I meet this problem again   
node v6.10.0 ; npm 4.2.0
Windows10.0.14393
After displaying  'please wait a while for setting up the extension ' ,It returned  an error saying : [processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
How can I fix this problem?

**Comment by anseki** [comment] 2017-03-02 13:46
Hi @huyinjie,
It seems a duplicate of #24, #20, #7.
If you need, please comment to #7, not here.
