### ISSUE TITLE
Cannot start Color Picker on Ubuntu 

### ISSUE THREAD

**Issue by yovchenko** [anseki/vscode-color#58] opened 2017-09-29 17:51 UTC
Hello.I have a trouble with Color Picker on my PC.It doesn't work!Any advise or guidance would be greatly appreciated.
- Extension Version: Color Picker 0.4.5
- VS Code Version: 1.16.1
- OS Version: Ubuntu 17.04
- Node.js Version (result of command `node -v`): 4.7.2
- NPM Version (result of command `npm -v`): 3.5.2

Steps to Reproduce:

1. Install extension Color Picker.
2. Launch the extension using Alt + C  P or Ctrl+Shift+P and Pick color.

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[-1506705698673.log](https://github.com/anseki/vscode-color/files/1345138/-1506705698673.log)


```

**Comment by anseki** [comment] 2017-09-30 04:09
Hi @yovchenko,

It seems that this is a duplicate of https://github.com/anseki/vscode-color/issues?q=is%3Aissue%20ansi.
It seems that your NPM was broken. Try to re-install NPM.

Please read https://github.com/anseki/vscode-color/issues/10.
And please comment to https://github.com/anseki/vscode-color/issues/10 (NOT here) if you need.

**Closed as completed by anseki** 2017-09-30 04:09 UTC
