### ISSUE TITLE
Error: Cannot get NPM

### ISSUE THREAD

**Issue by GilbertoBitt** [anseki/vscode-color#19] opened 2016-12-06 14:21 UTC
- Extension Version: 0.2.2
- VS Code Version: 1.7.2
- OS Version: Windows Server 2008 R2 Enterprise
- Node.js Version (result of command `node -v`): v6.9.1
- NPM Version (result of command `npm -v`): 3.10.8

Steps to Reproduce:

1. create c# code on unity
2. press Alt + C P.

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
extensionHost.ts:255 [Extension Host] Error: Cannot get NPM
    at initModule (C:\Users\Fundação\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:220:28)
    at getHostCmd (C:\Users\Fundação\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:331:9)
    at C:\Users\Fundação\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:394:19
    at Object.exports.sendRequest (C:\Users\Fundação\.vscode\extensions\anseki.vscode-color-0.2.2\node_modules\process-bridge\process-bridge.js:468:34)
    at pickConvert (C:\Users\Fundação\.vscode\extensions\anseki.vscode-color-0.2.2\lib\color-helper.js:180:15)
    at exports.pick (C:\Users\Fundação\.vscode\extensions\anseki.vscode-color-0.2.2\lib\color-helper.js:220:24)
    at t.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:25694)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:10602)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:21356)
    at p (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:22033)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)I.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
messageService.ts:128 [processBridge]: Error: Cannot get NPMe.doShow @ messageService.ts:128e.show @ messageService.ts:107(anonymous function) @ mainThreadMessageService.ts:55n.Class.derive._oncancel @ winjs.base.raw.js:1641t.$showMessage @ mainThreadMessageService.ts:25e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

messageService.ts:128 [processBridge]: Error: Cannot get NPMe.doShow @ messageService.ts:128e.show @ messageService.ts:107(anonymous function) @ mainThreadMessageService.ts:55n.Class.derive._oncancel @ winjs.base.raw.js:1641t.$showMessage @ mainThreadMessageService.ts:25e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
5extensionHost.ts:255 [Extension Host] makeRequest: command=/typelookup
```

**Comment by anseki** [comment] 2016-12-06 15:05
Hi @gilbertobitt,
It seems that this is a duplicate of #14.
Please read that issue, and comment to that if you need.
And also, that seems a part of log.

**Closed as completed by anseki** 2016-12-06 15:05 UTC

**Comment by GilbertoBitt** [comment] 2016-12-06 17:50
but in there the user have installed node.js to work properly and i do have it installed.. and updated.. even so i receive error.

**Comment by anseki** [comment] 2016-12-06 18:18
Please comment to #14, and also, that seems a part of log.

**Comment by kegi** [comment] 2022-01-06 18:53
I think this issue should be re-open. I do have npm and nodejs installed. All my others extensions are working fine.

**Comment by anseki** [comment] 2022-01-07 04:29
Hi @kegi, thank you for the comment.
If you give information, I might be able to help you.
https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md
And, please comment to #14.
