### ISSUE TITLE
Color Picker Error processBridge Cannot find module 'ansi'

### ISSUE THREAD

**Issue by MatFluor** [anseki/vscode-color#16] opened 2016-10-30 09:47 UTC
- Extension Version: Current
- VS Code Version: 1.6.1
- OS Version: Ubuntu 16.04
- Node.js Version (result of command `node -v`): (nodejs -v) 4.2.6
- NPM Version (result of command `npm -v`): 3.5.2

Steps to Reproduce:
1. Mark e.g. rgba(255, 255, 255, 0) in CSS
2. Command Pallete -> Color Picker
3. Error: [processBridge] Error: Cannot find module 'ansi'

Log:
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)

```
Error: Cannot find module 'ansi'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function.N.n._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:19970)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/npm/lib/ls.js:15:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.N.n._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:19970)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/npm/lib/install.js:110:10)
    at Module._compile (module.js:556:32)
```

**Comment by anseki** [comment] 2016-10-30 10:59
Hi @MatFluor,
It seems that this is a duplicate of #10.
Please read that issue, and check your NPM.
And comment to that issue, also, show me line 15 of `/usr/share/npm/lib/ls.js`.

**Closed as completed by anseki** 2016-10-30 10:59 UTC
