### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\Licardo\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\path.txt' 

### ISSUE THREAD

**Issue by L1cardo** [anseki/vscode-color#68] opened 2018-01-10 07:08 UTC
- Extension Version:0.4.5
- VS Code Version:1.19.1
- OS Version:Windows 10
- Node.js Version (result of command `node -v`):6.4.0
- NPM Version (result of command `npm -v`):5.6.0

Steps to Reproduce:

1. Installed color picker from extensions panel
2. Pressed key Alt C P

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)

[The error photo](https://user-images.githubusercontent.com/33802186/34759940-b3dbaee2-f618-11e7-8365-b3d66dfe9cca.png)

**Comment by anseki** [comment] 2018-01-10 07:17
Hi @L1cardo, thank you for the report.

It seems that this is a duplicate of [past issues](https://github.com/anseki/vscode-color/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22ENOENT%22%20%22path.txt%22).
The Electron in your computer is broken. Re-install the extension.
And please comment to #7 (not here) about this issue if you need.

**Closed as completed by anseki** 2018-01-10 07:17 UTC

**Comment by regs01** [comment] 2018-01-22 22:02
I got literally same. 
VSC 1.19.2 
node-v: 9.4.0
npm -v: 5.6.0, though it seem picking VSC's node.js


(code bbcode seem bugs a bit)
`
[Extension Host] Start child process...
console.ts:123 [Extension Host] Start initializing module...
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:123 [Extension Host] Node.js@7.9.0
console.ts:123 [Extension Host] Error: Cannot find module 'npm'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.J.X.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:490:709)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at getNpm (C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:139:15)
	at initModule (C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:220:10)
	at getHostCmd (C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:331:9)
	at C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
	at Object.exports.sendRequest (C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
	at pickConvert (C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
	at exports.pick (C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:416:270)
	at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:516:87)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:580)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:357:270)
console.ts:123 [Extension Host] Continue trying to get NPM...
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:123 [Extension Host] Try to get NPM via usage info.
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:123 [Extension Host] NPM@5.6.0
console.ts:123 [Extension Host] NPM directory path: C:\Program Files\nodejs\node_modules\npm
console.ts:123 [Extension Host] NPM resolved path: C:\Program Files\nodejs\node_modules\npm\lib\npm.js
console.ts:123 [Extension Host] Base directory path: C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5
console.ts:123 [Extension Host] Retry (Error: Cannot find module 'electron-prebuilt')
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:123 [Extension Host] Try to load: C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:391
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\esparse -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\esprima\bin\esparse.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\esvalidate -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\esprima\bin\esvalidate.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\mkdirp -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\mkdirp\bin\cmd.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\ncp -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\ncp\bin\ncp
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\semver -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\semver\bin\semver
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\strip-indent -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\strip-indent\cli.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\rc -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\rc\cli.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\sshpk-sign -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\sshpk\bin\sshpk-sign
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\sshpk-conv -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\sshpk\bin\sshpk-conv
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\sshpk-verify -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\sshpk\bin\sshpk-verify
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\uuid -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\uuid\bin\uuid
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\pretty-bytes -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\pretty-bytes\cli.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\rimraf -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\rimraf\bin.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\nugget -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\nugget\bin.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\electron-download -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-download\cli.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\extract-zip -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\extract-zip\cli.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\electron -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\cli.js
console.ts:123 [Extension Host] C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\js-yaml -> C:\Users\user\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\js-yaml\bin\js-yaml.js
extensionHost.ts:200 [Extension Host] debugger inspector at Downloading electron-v0.37.3-win32-x64.zip
0.0% (0 B/s)
...
100.0% of 47 MB (4.95 MB/s)

console.ts:123 [Extension Host] added 151 packages in 16.35s
console.ts:123 [Extension Host] Check version of: electron-prebuilt
console.ts:123 [Extension Host] Check version of: comma-separated-values
console.ts:123 [Extension Host] Check version of: js-yaml
console.ts:123 [Extension Host] Check version of: process-bridge
console.ts:123 [Extension Host] Try to send IPC message: 1
console.ts:123 [Extension Host] Try to send IPC message: 2
console.ts:123 [Extension Host] Child process disconnected
console.ts:123 [Extension Host] Child process exited with code: 0
`

**Comment by anseki** [comment] 2018-01-23 00:14
Hi @regs01, thank you for the report.
So, what is the same?

**Comment by regs01** [comment] 2018-01-23 00:48
Seem posted into wrong tab/issue. Further search by "Try to send IPC message" brought to colorHelper.disableGpu option. It works. Probably readme.md should list some major issues and how to deal with them.

**Comment by anseki** [comment] 2018-01-23 02:34
@regs01, thank you for the report.
So, did your issue be solved?
If you have an issue, you can make new issue at here: https://github.com/anseki/vscode-color/issues/new
We might be able to help you.
Also, you can update README and send the PR.
