### ISSUE TITLE
Error when launching the extension

### ISSUE THREAD

**Issue by minkir014** [anseki/vscode-color#87] opened 2019-05-26 23:50 UTC
when I pick the command `pick color` it shows that error
`[processBridge]: Error: ENOENT: no such file or directory, open 'C:\Users\MIN\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\path.txt'`

**Comment by anseki** [comment] 2019-05-27 01:45
Hi @minkir014, thank you for the report.

It seems that this is a duplicate of [past issues](https://github.com/anseki/vscode-color/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22ENOENT%22%20%22path.txt%22).
The Electron in your computer is broken. Re-install the extension. See: https://github.com/anseki/vscode-color/issues/7#issuecomment-311330975
And please comment to #7 (not here) about this issue if you need.
Also, please write with [the template](https://github.com/anseki/vscode-color/blob/master/.github/ISSUE_TEMPLATE.md) that was already shown if you will comment.

**Closed as completed by anseki** 2019-05-27 01:45 UTC
