### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ahsane** [anseki/vscode-color#84] opened 2019-04-10 09:37 UTC
- Extension Version: 0.4.5
- VS Code Version: 1.33.0
- OS Version: Win 10
- Node.js Version (result of command `node -v`): 10.15.0
- NPM Version (result of command `npm -v`): 6.4.1

Steps to Reproduce:

1. Download extension
2.  Run command pick color

Log (All lines):
```
Error: ENOENT: no such file or directory, open 'c:\Users\Ahsan\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\path.txt'
	at Object.fs.openSync (fs.js:577:3)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
	at Object.fs.readFileSync (fs.js:483:33)
	at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:563:29)
	at Object.<anonymous> (c:\Users\Ahsan\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\index.js:4:42)
	at Object.<anonymous> (c:\Users\Ahsan\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\index.js:6:3)
	at Module.t._initNodeRequire.r._compile (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:16:90)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Function.t._load (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:729:537)
	at Function.t.getExtensionPathIndex.then.a._load (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:691:639)
	at Function.t.getExtensionPathIndex.then.r._load (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:655:197)
	at Module.require (internal/modules/cjs/loader.js:658:17)
	at getHostCmd (c:\Users\Ahsan\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:316:41)
	at c:\Users\Ahsan\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:394:19
	at Object.exports.sendRequest (c:\Users\Ahsan\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\process-bridge\process-bridge.js:468:34)
	at pickConvert (c:\Users\Ahsan\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:187:15)
	at exports.pick (c:\Users\Ahsan\.vscode\extensions\anseki.vscode-color-0.4.5\lib\color-helper.js:229:24)
	at d._executeContributedCommand (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:477:621)
	at d.$executeContributedCommand (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:478:6)
	at d._doInvokeHandler (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:394)
	at d._receiveOneMessage (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Users\Ahsan\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)

[processBridge]: Error: ENOENT: no such file or directory, open 'c:\Users\Ahsan\.vscode\extensions\anseki.vscode-color-0.4.5\node_modules\electron-prebuilt\path.txt'
```

**Comment by anseki** [comment] 2019-04-10 09:55
Hi @AhsanE, thank you for the report.

It seems that this is a duplicate of [past issues](https://github.com/anseki/vscode-color/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22ENOENT%22%20%22path.txt%22).
The Electron in your computer is broken. Re-install the extension. See: https://github.com/anseki/vscode-color/issues/7#issuecomment-311330975
And please comment to #7 (not here) about this issue if you need.

**Closed as completed by anseki** 2019-04-10 09:55 UTC

**Comment by ahsane** [comment] 2019-04-10 10:05
Hello @anseki ,
I'm writing my fix for this.

***[@anseki edited]***
Thank you for your comment.
However that is a duplicate of https://github.com/anseki/vscode-color/issues/7#issuecomment-311330975, and also that contains incorrect information, and also this issue bears no relation to GPU.
Then, I removed that to avoid confusion.

**Comment by ahsane** [comment] 2019-04-10 10:24
Please don't remove my comment. I tried the previous solution. It was a part of the problem. But the GPU issue was also a part of the problem. 

Both were done to fix this.

**Comment by anseki** [comment] 2019-04-10 10:24
Of course I understand your kindness, and thank you. :smile:

**Comment by anseki** [comment] 2019-04-10 10:30
The GPU issue is not a part of this issue. That is independent issue, and it was already made. Also, that bears no relation to this issue.

**Comment by ahsane** [comment] 2019-04-10 11:19
@anseki  The thing is that in my personal case, both were the issue. The first issue was this. I followed the instructions. Even then it would not open, and would give no errors. Then I tried tinkering with GPU settings, and it worked. 

Obviously the log does not indicate that it was a GPU issue because the error in the log was caused by corrupt electron cache or corrupt extension file. 

After fixing that, there was no error on  'Pick Color' command. But it failed silently. It was a GPU problem as well, and I rechecked it by enabling GPU and vscode-color would not work with enabled GPU.

**Comment by anseki** [comment] 2019-04-10 11:43
I see.
Your computer had two problems:
+ Your cache data is broken.
+ Your GPU driver have a problem.

Anyway, those are unrelated to each other. 
Then, your comment about cache data contains incorrect information (path to cache, etc), and that is a duplicate of past issue.
Also, your comment about GPU issue is a duplicate of past issue, and that is unrelated to this issue.
Unrelated issues should be separated.

Therefore, I had to remove that to avoid confusion.
Please understand that.
