### ISSUE TITLE
[processBridge]: Error: Cannot find module 'ansi'

### ISSUE THREAD

**Issue by trubachoff** [anseki/vscode-color#55] opened 2017-08-22 11:49 UTC
- Extension Version: 0.4.5
- VS Code Version: 1.15.1
- OS Version: Ubuntu 16.10
- Node.js Version (result of command `node -v`): v8.1.3
- NPM Version (result of command `npm -v`): 5.0.3

Steps to Reproduce:

1. Run picker from Comand panel or shortcut

**Comment by anseki** [comment] 2017-08-22 12:19
Hi @trubachoff,
It seems that this is a duplicate of https://github.com/anseki/vscode-color/issues?q=is%3Aissue%20%22ansi%22%20.
It seems that your NPM was broken.
Please read https://github.com/anseki/vscode-color/issues/10, and check your NPM.
And please comment to https://github.com/anseki/vscode-color/issues/10 (NOT here) if you need.

**Closed as completed by anseki** 2017-08-22 12:19 UTC
