### ISSUE TITLE
Suddenly stopped working, Child process already exited

### ISSUE THREAD

**Issue by natew** [anseki/vscode-color#59] opened 2017-10-04 20:28 UTC
- Extension Version: latest
- VS Code Version: latest
- OS Version: mac sierra
- Node.js Version (result of command `node -v`): 8.5
- NPM Version (result of command `npm -v`): 5.5

Not sure why this started happening, but I tired reinstalling and restarting a few times.

![image](https://user-images.githubusercontent.com/12100/31198073-e1f459fe-a907-11e7-9f18-76bd34df1940.png)

![image](https://user-images.githubusercontent.com/12100/31198075-e4ebd5ba-a907-11e7-84f6-825b20cd5755.png)

**Comment by natew** [comment] 2017-10-04 20:29
Actually got this now:

![image](https://user-images.githubusercontent.com/12100/31198110-08857bb6-a908-11e7-814f-4bfaafe1cf14.png)

**Comment by anseki** [comment] 2017-10-05 05:37
Hi @natew, thank you for the report.

It seems that the Electron in your computer is broken. Or, the electron and another electron might conflict if you have installed Electron globally before.
That should not be installed globally because various apps may not work by the confliction.

Try to remove that. (except there are special reasons)

```
npm uninstall -g electron
npm uninstall -g electron-prebuilt

cd ~/.vscode/extensions/anseki.vscode-color-0.4.5
npm uninstall electron-prebuilt
```

And execute `Pick Color` command on VS Code.

**Comment by daviholandas** [comment] 2017-10-05 07:22
Extension Version: latest
VS Code Version: latest
OS Version: mac sierra
![captura de tela 2017-10-05 as 04 16 27](https://user-images.githubusercontent.com/26368905/31214958-0be1e458-a984-11e7-8f02-7637c856f82a.png)
I already deactivated the option "http.proxyStrictSSL": false, but same error happen.

**Comment by natew** [comment] 2017-10-05 18:13
That didn't seem to help.

![image](https://user-images.githubusercontent.com/12100/31243155-37eb604e-a9be-11e7-9b7c-687b2b75cce1.png)

Tried re-installing electron-prebuilt into anseki.vs-code dir but still seems to be broken.

**Comment by natew** [comment] 2017-10-05 18:14
After restart:

![image](https://user-images.githubusercontent.com/12100/31243209-638ef116-a9be-11e7-9195-0f7e771fc281.png)

**Comment by natew** [comment] 2017-10-05 18:15
After restart:

![image](https://user-images.githubusercontent.com/12100/31243223-72260a0c-a9be-11e7-9218-f6d8a506ef4e.png)

**Comment by anseki** [comment] 2017-10-05 18:50
At least, it seems that the confliction in your computer was solved.
And that installation failed.
It seems that the error is a duplicate of [past issues](https://github.com/anseki/vscode-color/issues?q=is%3Aissue%20%22ENOENT%22%20%22path.txt%22).
Cache data in your computer might be broken. You can clear the cache data by this:

1. Uninstall the extension.
2. Command to remove NPM cache data.  
`npm cache clean`
3. Command to confirm the cache data were cleared.  
`npm cache ls`
4. Remove Electron cache data in `~/.electron`.
5. Re-install the extension.

**Comment by anseki** [comment] 2017-10-11 06:50
No reply came. I close this issue.

**Closed as completed by anseki** 2017-10-11 06:50 UTC
