### ISSUE TITLE
[processBridge]: Error: ENOENT: no such file or directory, open 'C:\Users\admin\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\path.txt'

### ISSUE THREAD

**Issue by dinglei5959** [anseki/vscode-color#39] opened 2017-06-02 03:36 UTC
- Extension Version:0.4.1
- VS Code Version:1.12.2
- OS Version:window 10.0  v10240
- Node.js Version (result of command `node -v`):v4.4.4
- NPM Version (result of command `npm -v`):v4.1.1

Steps to Reproduce:

1. ctrl+c    p 
2. the error happened

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```

```

**Comment by dinglei5959** [comment] 2017-06-02 03:38
why  is this?it seems  there should be a config

**Comment by anseki** [comment] 2017-06-02 05:16
Hi @dinglei5959, thank you for the report.
Could you please give information?
Because the Electron in your computer may be broken.
That is, see this https://github.com/anseki/vscode-color/issues/39#issue-233067968.

**Comment by dinglei5959** [comment] 2017-06-02 05:45
what  the  Electron  should be?

**Comment by anseki** [comment] 2017-06-02 05:57
It seems that this is a duplicate of #7.
The Electron in your computer is broken. Re-install the extension.
And please comment to #7 about this issue if you need.

**Closed as completed** 2017-06-02 05:59 UTC
