### ISSUE TITLE
Error when run: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by kuanyui** [anseki/vscode-color#77] opened 2018-11-21 08:00 UTC
- Extension Version: `0.4.5`
- VS Code Version: `1.27.1`
- OS Version: Latest Chakra Linux (rolling upgrading, similar to Archlinux)
- Node.js Version (result of command `node -v`): `8.9.3` (within `nvm`)
- NPM Version (result of command `npm -v`): `5.0.0` (within `nvm`)

Steps to Reproduce:
1. Open terminal, `nvm use v8.9.3` (Same with the Electron version of this VSCode version), then `code` to startup VSCode.
1. Install from VSCode, wait for > 2 minutes (I cannot see any outputs, but 2 minutes should be enough to finish I guess?)
2. Restart VSCode
3. Run extension, show error: 
```
[processBridge]: Error: ENOENT: no such file or directory, open '/home/onohiroko/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/path.txt'
```

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Start child process...
workbench.main.js:sourcemap:276 [Extension Host] Error: ENOENT: no such file or directory, open '/home/onohiroko/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/path.txt'
	at Object.fs.openSync (fs.js:646:18)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
	at Object.fs.readFileSync (fs.js:551:33)
	at Object.fs.readFileSync (ELECTRON_ASAR.js:545:29)
	at Object.<anonymous> (/home/onohiroko/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/index.js:4:42)
	at Object.<anonymous> (/home/onohiroko/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/index.js:6:3)
	at Module._compile (module.js:642:30)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:847:582)
	at Function.o._load (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:795:924)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at getHostCmd (/home/onohiroko/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:316:41)
	at /home/onohiroko/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:394:19
	at Object.exports.sendRequest (/home/onohiroko/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/process-bridge/process-bridge.js:468:34)
	at pickConvert (/home/onohiroko/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:187:15)
	at exports.pick (/home/onohiroko/.vscode/extensions/anseki.vscode-color-0.4.5/lib/color-helper.js:229:24)
	at e._executeContributedCommand (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:726:706)
	at e.$executeContributedCommand (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:727:212)
	at e._doInvokeHandler (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/home/onohiroko/.vscode/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
t.log @ workbench.main.js:sourcemap:276
t._logExtensionHostMessage @ workbench.main.js:sourcemap:3151
(anonymous) @ workbench.main.js:sourcemap:3147
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
workbench.main.js:sourcemap:2407 [processBridge]: Error: ENOENT: no such file or directory, open '/home/onohiroko/.vscode/extensions/anseki.vscode-color-0.4.5/node_modules/electron-prebuilt/path.txt'
```

**Comment by anseki** [comment] 2018-11-21 08:23
Hi @kuanyui, thank you for the report.

It seems that this is a duplicate of [past issues](https://github.com/anseki/vscode-color/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22ENOENT%22%20%22path.txt%22).
The Electron in your computer is broken. Re-install the extension.
And please comment to #7 (not here) about this issue if you need.

**Closed as completed by anseki** 2018-11-21 08:23 UTC
