### ISSUE TITLE
[processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js` i get this error when I try to pick a color 

### ISSUE THREAD

**Issue by Abdullah-AlAttar** [anseki/vscode-color#38] opened 2017-05-29 19:22 UTC
- Extension Version:
- VS Code Version:
- OS Version:
- Node.js Version (result of command `node -v`):
- NPM Version (result of command `npm -v`):

Steps to Reproduce:

1. 
2. 

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] TextEditor is closed/disposed
d.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:29 [Extension Host] Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1
    at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
d.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:28 [processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1
e.doShow @ workbench.main.js:28
```

**Comment by anseki** [comment] 2017-05-29 23:55
Hi @Abdullah-AlAttar, thank you for the report.
Could you please give me more information? That is, all headers in the your comment. https://github.com/anseki/vscode-color/issues/38#issue-232084648

**Comment by Abdullah-AlAttar** [comment] 2017-05-30 13:11
Extension Version: latest 
VS Code Version:1.12.2
OS Version:Windows 10 pro 64-bit(10.0,Build 15063)
Node.js Version (result of command node -v): v6.10.3
NPM Version (result of command npm -v):3.10.10

**Comment by anseki** [comment] 2017-05-30 13:40
It seems a duplicate of https://github.com/anseki/vscode-color/issues?utf8=%E2%9C%93&q=is%3Aissue%20postinstall.
Please comment to #7 if you need, not here.

**Closed as completed by anseki** 2017-05-30 13:40 UTC
