### ISSUE TITLE
Invisible Color Picker Dialog Issue

### ISSUE THREAD

**Issue by hysmio** [anseki/vscode-color#29] opened 2017-04-16 16:06 UTC
I try and use the command to bring up the dialog, but it never draws to the screen, it's there as you can see in the screenshot, but I can't see it.

- Extension Version: 0.2.6
- VS Code Version: 1.11.2
- OS Version: Windows 10
- Node.js Version (result of command `node -v`): 6.10.2
- NPM Version (result of command `npm -v`): 3.10.10

Steps to Reproduce:

1. Install
2. Alt + C  P

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
```
[Extension Host] Start child process...
extensionHost.ts:284 [Extension Host] Check version of: electron-prebuilt
extensionHost.ts:284 [Extension Host] Check version of: comma-separated-values
extensionHost.ts:284 [Extension Host] Check version of: js-yaml
extensionHost.ts:284 [Extension Host] Check version of: process-bridge
extensionHost.ts:284 [Extension Host] Try to send IPC message: 5
extensionHost.ts:284 [Extension Host] Try to send IPC message: 6
extensionHost.ts:284 [Extension Host] Child process disconnected
extensionHost.ts:284 [Extension Host] Child process exited with code: 0
```
![image](https://cloud.githubusercontent.com/assets/26195151/25072471/5b44653c-2312-11e7-8c62-3595360d297f.png)

**Comment by anseki** [comment] 2017-04-16 18:21
Hi @saucymoose, thank you for the report.

Could you tell me these?:

- When the cursor (not mouse cursor) is positioned on a place that is not a color string, press `Alt + C P` keys, and wait a few seconds before pressing the Enter key. Then, is a color string inserted at the cursor position? I mean, I have to know whether the dialog box is not opened or it's invisible but it is opened.
- Does a [`Convert Color`](https://github.com/anseki/vscode-color#convert-color) command work?
- Try to re-install the extension.

**Comment by hysmio** [comment] 2017-04-17 04:22
When I use the color picker, I can select colours and they are input correctly and it all works, I just can't see the dialog.

Yes, Convert Color works perfectly.

I've tried re-installing a few times but unfortunately I wasn't able to get it to work.

**Comment by anseki** [comment] 2017-04-17 10:50
I see.
It seems that the Electron doesn't work in your computer.

The Electron might have been not removed when you re-installed the extension.
Try this to re-install the extension:

1. Close VS Code.
2. Remove `%username%\.vscode\extensions\anseki.vscode-color-0.2.6` folder.
3. Install Color Picker again.

If another Electron was already installed globally, that might conflict. That should not be installed globally because various apps may not work by the confliction.
If you installed Electron globally, try to remove that. (except there are special reasons)

```
npm uninstall -g electron
npm uninstall -g electron-prebuilt
```

**Comment by hysmio** [comment] 2017-04-17 11:01
I uninstalled both `electron` and `electron-prebuilt` and reinstalled using those steps, but still couldn't get it to show the dialog, same issue.

**Comment by anseki** [comment] 2017-04-17 11:19
Do you mean that another Electron was already installed globally?

**Comment by hysmio** [comment] 2017-04-17 11:20
I think it may have been, yes.

**Comment by hysmio** [comment] 2017-04-17 11:20
When using the uninstall command, it just took a second and then finished, no confirmation or error.

**Comment by anseki** [comment] 2017-04-17 11:59
You can check the Electron that was installed globally.

1. Press `Ctrl + @` in VS Code. Then a terminal is opened.
2. In the terminal, run this command: `node -e "console.log(require('electron-prebuilt'))"`

Then an error `Error: Cannot find module 'electron-prebuilt'` should occur.

And run these commands in CMD:

```
cd "C:\Users\<USER_NAME>\.vscode\extensions\anseki.vscode-color-0.2.6"
node -e "console.log(require('electron-prebuilt'))"
```

(Replace `<USER_NAME>` with your user name.)


Then `C:\Users\<USER_NAME>\.vscode\extensions\anseki.vscode-color-0.2.6\node_modules\electron-prebuilt\dist\electron.exe` should be shown.

**Comment by hysmio** [comment] 2017-04-17 12:03
Yep the error occurred when using the first command.

The correct output did come out from running the second command.

**Comment by anseki** [comment] 2017-04-17 15:24
Hmm...
I don't know this case...

npm cache might be broken.
You can clear the cache by this command. (Remove the extension before this.)

```
npm cache clean
```

You should confirm the cache cleared by this command:

```
npm cache ls
```

Also, remove Electron cache in `C:\Users\<USER_NAME>\.electron`

**Comment by hysmio** [comment] 2017-04-17 15:29
Unfortunately, still no fix.

**Comment by anseki** [comment] 2017-04-17 16:09
This is a test script to open the dialog box directly.
Save this to a `C:\Users\<USER_NAME>\.vscode\extensions\anseki.vscode-color-0.2.6\test.js` file.

```js
process.stdin.on('error', error => { throw error; });
process.stdin.on('close', () => { process.exit(); });
require('process-bridge').sendRequest({command: 'pick'},
    [require('path').join(__dirname, 'lib/app.asar')], error => {
  if (error) {
    if (error.isRetried) { return; }
    throw error;
  }
  process.exit();
});
```

And, run these in CMD:

```
cd C:\Users\<USER_NAME>\.vscode\extensions\anseki.vscode-color-0.2.6
node test
```

**Comment by hysmio** [comment] 2017-04-17 16:16
Oddly enough, the window is there, however the window is still invisible.

My screenshot program is even recognising the window.

![image](https://cloud.githubusercontent.com/assets/26195151/25094999/fceadaea-23dc-11e7-9fff-41038ffc286c.png)

**Comment by anseki** [comment] 2017-04-17 16:48
Yes, it's strange...
It seems that the Electron and the extension work fine, and only its rendering doesn't work.
Your display or its GPU driver might have a problem.
Check whether a version of the driver that you use is old.

**Comment by hysmio** [comment] 2017-04-18 13:42
Nah I keep my drivers up to date always.

**Comment by anseki** [comment] 2017-04-18 15:27
I think that your GPU driver might have a bug.
Before, I saw a case of a driver for Linux that can't render the window by a bug.
And never did I see such your case.

**Comment by hysmio** [comment] 2017-04-18 15:32
Yeah probably just an odd issue with my system, no worries! Feel free to close since it isn't an issue with the application!

**Comment by anseki** [comment] 2017-04-18 16:35
I found a information that says transparent windows don't work when DWM is disabled in Windows OS.
The DWM should be enabled since Windows Vista. However, that might be disabled if your computer was upgraded from older Windows.
Check that in your computer by Task Manager.
Right click the taskbar, click on "Task Manager". And find `dwm.exe` in "Details" tab.

**Comment by shiamalon** [comment] 2017-04-20 14:43
Hey,

I have exactly the same issue and I have the DWM running, color picker windows doesn't show up but its there when I mouse over. Using windows 10.

:|

**Comment by anseki** [comment] 2017-04-20 15:20
Hi @shiamalon, thank you for the report.

Try to specify `1` for [`colorHelper.disableGpu`](https://github.com/anseki/vscode-color#colorhelperdisablegpu) option.
And please tell me if something changes.

**Comment by shiamalon** [comment] 2017-04-20 15:45
@anseki it worked! Thanks!

Please let me know if you need someone to test and try plugin developments or features. I will be glad to help!

**Comment by anseki** [comment] 2017-04-20 16:05
I'm glad that it was solved. 😄 
And thank you for your help.
I guess that this issue is caused by an upstream bug that GPU driver has problem.
I think that your Windows was upgraded from older Windows.

**Comment by anseki** [comment] 2017-04-26 10:47
No reply and helping came, and I close this issue.

**Closed as completed by anseki** 2017-04-26 10:47 UTC

**Comment by RacerDelux** [comment] 2017-08-09 16:33
I would like to mention I had this exact same issue, Surface laptop upgraded from windows S to pro. The disable gpu worked for me.

**Comment by anseki** [comment] 2017-08-10 01:36
Hi @RacerDelux, thank you for the report.
So, do you mean that the issue in your computer was solved by the `colorHelper.disableGpu` option?

**Comment by RacerDelux** [comment] 2018-02-21 16:51
Yes that is correct

**Comment by anseki** [comment] 2018-02-21 16:59
I was relieved.
Thank you :smile:
