### ISSUE TITLE
[processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`

### ISSUE THREAD

**Issue by mihail-karimov** [anseki/vscode-color#49] opened 2017-06-27 10:47 UTC
- Extension Version: v0.4.1
- VS Code Version: v1.13.1
- OS Version: windows 7 x64 (6.1 build 7601)
- Node.js Version: v6.11.0
- NPM Version: 3.10.10

![dd](https://user-images.githubusercontent.com/25096465/27583960-ae294bee-5b4f-11e7-960d-bf0f202d289f.png)

Log (All lines):
(Click menu of VS Code "Help > Toggle Developer Tools", and click "Console" tab)
[Extension Host] Continue trying to get NPM...
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] Try to get NPM via usage info.
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] NPM@3.10.10
extensionHost.ts:293[Extension Host] NPM directory path: C:\Program Files\nodejs\node_modules\npm
extensionHost.ts:293[Extension Host] NPM resolved path: C:\Program Files\nodejs\node_modules\npm\lib\npm.js
extensionHost.ts:293[Extension Host] Base directory path: C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1
extensionHost.ts:293[Extension Host] Retry (Error: Cannot find module 'electron-prebuilt')
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] Try to load: C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\esvalidate -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\esprima\bin\esvalidate.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\esparse -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\esprima\bin\esparse.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\mkdirp -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\mkdirp\bin\cmd.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\ncp -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\ncp\bin\ncp
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\semver -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\semver\bin\semver
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\strip-indent -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\strip-indent\cli.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\rc -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\rc\index.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\sshpk-sign -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\sshpk\bin\sshpk-sign
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\sshpk-conv -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\sshpk\bin\sshpk-conv
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\sshpk-verify -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\sshpk\bin\sshpk-verify
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\uuid -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\uuid\bin\uuid
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\pretty-bytes -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\pretty-bytes\cli.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\rimraf -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\rimraf\bin.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\nugget -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\nugget\bin.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\electron-download -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-download\cli.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\extract-zip -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\extract-zip\cli.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\electron -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\electron-prebuilt\cli.js
extensionHost.ts:293[Extension Host] C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\js-yaml -> C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1\node_modules\js-yaml\bin\js-yaml.js
extensionHost.ts:293[Extension Host] Spawn in silent-mode: C:\Windows\system32\cmd.exe /d /s /c node install.js
d.logExtensionHostMessage @ extensionHost.ts:293
27extensionHost.ts:293[Extension Host] TextEditor is closed/disposed
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293[Extension Host] vscode-color@0.4.1 C:\Users\User\.vscode\extensions\anseki.vscode-color-0.4.1
+-- comma-separated-values@3.6.4 
+-- js-yaml@3.8.4 
| +-- argparse@1.0.9 
| | `-- sprintf-js@1.0.3 
| `-- esprima@3.1.3 
`-- process-bridge@0.3.6 
  `-- semver@5.3.0 

extensionHost.ts:293[Extension Host] Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1
    at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
d.logExtensionHostMessage @ extensionHost.ts:293
messageService.ts:125[processBridge]: Error: electron-prebuilt@0.37.3 postinstall: `node install.js`
Exit status 1

**Comment by anseki** [comment] 2017-06-27 11:04
Hi @mihail-karimov, thank you for the comment.

It seems a duplicate of https://github.com/anseki/vscode-color/issues?utf8=%E2%9C%93&q=is%3Aissue%20postinstall.
Please comment to #7 if you need, not here.

**Closed as completed by anseki** 2017-06-27 11:04 UTC

**Comment by mihail-karimov** [comment] 2017-06-27 11:13
i deleted directory and install extension again, when i try to show dialog it says "setting up extensions" in the bottom. Then it shows error see in screenshot.
