### ISSUE TITLE
[processBridge]: Error: ENOENT: no such file or directory, open 'MYHOME/.vscode/extensions/anseki.vscode-color-0.1.9/node_modules/electron-prebuilt/path.txt'

### ISSUE THREAD

**Issue by xjchan** [anseki/vscode-color#8] opened 2016-08-14 16:10 UTC
The color picker does not wrok and throw an error like this "[processBridge]: Error: ENOENT: no such file or directory, open 'MYHOME/.vscode/extensions/anseki.vscode-color-0.1.9/node_modules/electron-prebuilt/path.txt'"

**Comment by anseki** [comment] 2016-08-14 17:40
Hi @xjchan, thank you for the report.

It seems that this is a duplicate of https://github.com/anseki/vscode-color/issues/7.
Try to do my recommendation in that issue, and please comment to that issue about this issue.

**Closed as completed by anseki** 2016-08-14 17:40 UTC
